In [2]:
import pandas as pd

In [8]:
daraz = pd.read_csv("./daraz_dataset.csv")

In [9]:
daraz

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.80,eSewa,3,Processing
496,DZ100497,2026-05-10,Ram Adhikari,35,Female,Bhaktapur,Electronics,Power Bank,4,5707,5,21686.60,Card,3,Cancelled
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.00,Khalti,3,Shipped
498,DZ100499,2026-01-22,Gita Shrestha,27,Female,Dharan,Beauty,Shampoo,5,2468,10,11106.00,IME Pay,2,Returned
499,DZ100500,2026-01-14,Rohit Adhikari,25,Male,Bhaktapur,Sports,Yoga Mat,2,38163,10,68693.40,IME Pay,4,Returned

In [10]:
daraz.shape

(500, 15)

In [11]:
daraz.columns

Index(['OrderID', 'OrderDate', 'CustomerName', 'Age', 'Gender', 'District',
       'Category', 'Product', 'Quantity', 'UnitPrice', 'DiscountPercent',
       'TotalAmount', 'PaymentMethod', 'Rating', 'OrderStatus'],
      dtype='object')

In [15]:
daraz.iloc[0]

OrderID                DZ100001
OrderDate            2026-03-04
CustomerName       Anita Basnet
Age                          24
Gender                     Male
District              Nepalgunj
Category                 Sports
Product                Football
Quantity                      1
UnitPrice                 48898
DiscountPercent              10
TotalAmount             44008.2
PaymentMethod           IME Pay
Rating                        1
OrderStatus           Delivered
Name: 0, dtype: object

In [18]:
daraz.iloc[0,2]

'Anita Basnet'

In [19]:
daraz.loc[:,"District"]

0      Nepalgunj
1        Pokhara
2       Lalitpur
3        Chitwan
4         Dharan
         ...
495    Nepalgunj
496    Bhaktapur
497      Itahari
498       Dharan
499    Bhaktapur
Name: District, Length: 500, dtype: object

In [ ]:
daraz.loc[(daraz["District"]=="Kathmandu") & (daraz["PaymentMethod"]=="eSewa")]

In [56]:
daraz.sort_values("TotalAmount",ascending=False)

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
375,DZ100376,2026-02-11,Asha Thapa,18,Male,Bhaktapur,Books,Notebook,5,45982,0,229910.00,IME Pay,5,Returned
271,DZ100272,2026-01-29,Ramesh Adhikari,41,Male,Itahari,Electronics,Bluetooth Speaker,5,46482,5,220789.50,IME Pay,5,Delivered
132,DZ100133,2026-02-04,Sita Rai,52,Female,Bhaktapur,Sports,Football,5,48481,10,218164.50,IME Pay,4,Shipped
435,DZ100436,2026-03-20,Nabin Rai,46,Male,Butwal,Home,Chair,5,43252,0,216260.00,eSewa,2,Shipped
472,DZ100473,2026-02-22,Sita Karki,42,Male,Kathmandu,Books,Python Basics,5,44649,5,212082.75,COD,1,Processing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,DZ100095,2026-03-02,Roshan Rai,19,Male,Biratnagar,Sports,Football,2,1273,10,2291.40,eSewa,2,Returned
492,DZ100493,2026-05-04,Kiran Sharma,55,Female,Lalitpur,Groceries,Coffee,1,2781,20,2224.80,Khalti,5,Cancelled
74,DZ100075,2026-03-18,Roshan Shrestha,49,Male,Butwal,Books,Notebook,3,468,10,1263.60,Card,4,Cancelled
195,DZ100196,2026-05-22,Manish Sharma,19,Female,Chitwan,Sports,Dumbbell,1,733,20,586.40,COD,1,Processing
27,DZ100028,2026-02-03,Rohit Basnet,46,Female,Chitwan,Books,Data Science 101,1,532,10,478.80,eSewa,1,Delivered

In [57]:
daraz

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.80,eSewa,3,Processing
496,DZ100497,2026-05-10,Ram Adhikari,35,Female,Bhaktapur,Electronics,Power Bank,4,5707,5,21686.60,Card,3,Cancelled
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.00,Khalti,3,Shipped
498,DZ100499,2026-01-22,Gita Shrestha,27,Female,Dharan,Beauty,Shampoo,5,2468,10,11106.00,IME Pay,2,Returned
499,DZ100500,2026-01-14,Rohit Adhikari,25,Male,Bhaktapur,Sports,Yoga Mat,2,38163,10,68693.40,IME Pay,4,Returned

In [ ]:
#dirty data

In [68]:
 daraz.isnull().sum() #missing value;
daraz.fillna(0) #making zero in nan place
daraz["UnitPrice"].fillna(daraz["UnitPrice"].mean())

0      48898
1      33418
2      46053
3      17635
4       3303
       ...
495    47942
496     5707
497    48890
498     2468
499    38163
Name: UnitPrice, Length: 500, dtype: int64

In [71]:
dummy = pd.Series(["100","200","aayush"])
pd.to_numeric(dummy,errors="coerce") #if there is alphabet in the series of number

0    100.0
1    200.0
2      NaN
dtype: float64

In [72]:
daraz

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.80,eSewa,3,Processing
496,DZ100497,2026-05-10,Ram Adhikari,35,Female,Bhaktapur,Electronics,Power Bank,4,5707,5,21686.60,Card,3,Cancelled
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.00,Khalti,3,Shipped
498,DZ100499,2026-01-22,Gita Shrestha,27,Female,Dharan,Beauty,Shampoo,5,2468,10,11106.00,IME Pay,2,Returned
499,DZ100500,2026-01-14,Rohit Adhikari,25,Male,Bhaktapur,Sports,Yoga Mat,2,38163,10,68693.40,IME Pay,4,Returned

In [83]:
#when abc like stopped our process
pd.to_numeric(daraz["UnitPrice"],errors = "coerce")
daraz["UnitPrice"].fillna(daraz["UnitPrice"].mean())

0      48898
1      33418
2      46053
3      17635
4       3303
       ...
495    47942
496     5707
497    48890
498     2468
499    38163
Name: UnitPrice, Length: 500, dtype: int64

In [90]:
daraz["coerce"]= pd.to_numeric(daraz["Rating"],errors = "coerce")
daraz["coerce"]= daraz["Rating"].fillna(daraz["Rating"].median())
daraz #avg rakherah treat garna ni sakinxa!

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus,coerce
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered,1
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled,5
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered,4
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled,5
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.80,eSewa,3,Processing,3
496,DZ100497,2026-05-10,Ram Adhikari,35,Female,Bhaktapur,Electronics,Power Bank,4,5707,5,21686.60,Card,3,Cancelled,3
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.00,Khalti,3,Shipped,3
498,DZ100499,2026-01-22,Gita Shrestha,27,Female,Dharan,Beauty,Shampoo,5,2468,10,11106.00,IME Pay,2,Returned,2
499,DZ100500,2026-01-14,Rohit Adhikari,25,Male,Bhaktapur,Sports,Yoga Mat,2,38163,10,68693.40,IME Pay,4,Returned,4

In [92]:
#drop garna nisakxa
daraz.dropna()

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus,coerce
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered,1
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled,5
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered,4
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled,5
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.80,eSewa,3,Processing,3
496,DZ100497,2026-05-10,Ram Adhikari,35,Female,Bhaktapur,Electronics,Power Bank,4,5707,5,21686.60,Card,3,Cancelled,3
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.00,Khalti,3,Shipped,3
498,DZ100499,2026-01-22,Gita Shrestha,27,Female,Dharan,Beauty,Shampoo,5,2468,10,11106.00,IME Pay,2,Returned,2
499,DZ100500,2026-01-14,Rohit Adhikari,25,Male,Bhaktapur,Sports,Yoga Mat,2,38163,10,68693.40,IME Pay,4,Returned,4

In [94]:
daraz.duplicated()
#duplication of data

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [100]:
#added of somethings..
daraz["District"].str.replace("%","",regex =False)

0      Nepalgunj
1        Pokhara
2       Lalitpur
3        Chitwan
4         Dharan
         ...
495    Nepalgunj
496    Bhaktapur
497      Itahari
498       Dharan
499    Bhaktapur
Name: District, Length: 500, dtype: object

In [ ]:
#outliers