In [13]:
import numpy as np
import pandas as pd

In [17]:
df = pd.DataFrame({
    "subject": ["math", "science", "english", "nepali"],
    "score": [98, 65, 76, 54]
})

In [18]:
df

   subject  score
0     math     98
1  science     65
2  english     76
3   nepali     54

In [20]:
for score in df["score"]:
    if score>=60:
        print("Pass")
    else:
        print("fail")

Pass
Pass
Pass
fail

In [21]:
df["score"].mean()

np.float64(73.25)

In [22]:
df["score"].describe()

count     4.000000
mean     73.250000
std      18.786076
min      54.000000
25%      62.250000
50%      70.500000
75%      81.500000
max      98.000000
Name: score, dtype: float64

In [28]:
mean_score = df["score"].mean()

df["mean_score"] = mean_score

print(df)

   subject  score  mean_score
0     math     98       73.25
1  science     65       73.25
2  english     76       73.25
3   nepali     54       73.25

In [34]:
mean_score = df["score"].mean()

df["above_average"] = df["score"] >= mean_score

for value in df["above_average"]:
    if value:
        print("True")
    else:
        print("False")
df

True
False
True
False

   subject  score  mean_score  above_average
0     math     98       73.25           True
1  science     65       73.25          False
2  english     76       73.25           True
3   nepali     54       73.25          False

In [41]:
True_data = df[df["above_average"]]
print(True_data)

   subject  score  mean_score  above_average
0     math     98       73.25           True
2  english     76       73.25           True

In [42]:
False_data= df[~df["above_average"]]
print(False_data)

   subject  score  mean_score  above_average
1  science     65       73.25          False
3   nepali     54       73.25          False