In [47]:
import pandas as pd

In [48]:
student = pd.DataFrame({
    "id": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name": [
        "Ram", "Shyam", "Hari", "Krish", "Manoj",
        "Sita", "Gita", "Rita", "Aayush", "Ramesh", "Suman"
    ],
    "city": [
        "Kathmandu", "Pokhara", "Butwal", "Biratnagar", "Dharan",
        "Nepalgunj", "Surkhet", "Janakpur", "Hetauda", "Bhaktapur", "Lalitpur"
    ]
})

score = pd.DataFrame({
    "id": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],   # 10 IDs
    "subject": [
        "Math",
        "Science",
        "English",
        "Computer",
        "Physics",
        "Chemistry",
        "Biology",
        "Economics",
        "History",
        "Geography"
    ],
    "score": [95, 88, 76, 99, 84, 91, 73, 80, 69, 87]
})

In [49]:
student

    id    name        city
0    0     Ram   Kathmandu
1    1   Shyam     Pokhara
2    2    Hari      Butwal
3    3   Krish  Biratnagar
4    4   Manoj      Dharan
5    5    Sita   Nepalgunj
6    6    Gita     Surkhet
7    7    Rita    Janakpur
8    8  Aayush     Hetauda
9    9  Ramesh   Bhaktapur
10  10   Suman    Lalitpur

In [52]:
score

   id    subject  score
0   0       Math     95
1   1    Science     88
2   2    English     76
3   3   Computer     99
4   4    Physics     84
5   5  Chemistry     91
6   6    Biology     73
7   7  Economics     80
8   8    History     69
9   9  Geography     87

In [53]:
merged_df = pd.merge(student, score, on="id")

print(merged_df)

   id    name        city    subject  score
0   0     Ram   Kathmandu       Math     95
1   1   Shyam     Pokhara    Science     88
2   2    Hari      Butwal    English     76
3   3   Krish  Biratnagar   Computer     99
4   4   Manoj      Dharan    Physics     84
5   5    Sita   Nepalgunj  Chemistry     91
6   6    Gita     Surkhet    Biology     73
7   7    Rita    Janakpur  Economics     80
8   8  Aayush     Hetauda    History     69
9   9  Ramesh   Bhaktapur  Geography     87

In [56]:
df[df["score"].mean()]

KeyError: np.float64(84.2)