In [2]:
import pandas as pd

In [5]:
df = pd.DataFrame({
    "player":["Ronaldo","Messi","Mbappe","Vinijr","Neymar","Belingham","Nunomendes"],
    "Goals":[1000,900,500,200,400,200,100],
    "Assists":[400,500,200,100,300,100,100],
    "Matches":[1100,1000,500,500,600,400,300],
})

In [6]:
df

       player  Goals  Assists  Matches
0     Ronaldo   1000      400     1100
1       Messi    900      500     1000
2      Mbappe    500      200      500
3      Vinijr    200      100      500
4      Neymar    400      300      600
5   Belingham    200      100      400
6  Nunomendes    100      100      300

In [27]:
gpm = []

for i in range(len(df)):
    goal_per_match = df.loc[i, "Goals"] / df.loc[i, "Matches"]
    gpm.append(goal_per_match)

df["Goal_per_match"] = gpm

print(df)

       player  Goals  Assists  Matches  Goal_per_match Above_Average_goals
0     Ronaldo   1000      400     1100        0.909091          Top player
1       Messi    900      500     1000        0.900000          Top player
2      Mbappe    500      200      500        1.000000          Top player
3      Vinijr    200      100      500        0.400000       Normal player
4      Neymar    400      300      600        0.666667       Normal player
5   Belingham    200      100      400        0.500000       Normal player
6  Nunomendes    100      100      300        0.333333       Normal player

In [32]:
total = 0

for goal in df["Goals"]:
    total += goal

average_goal = total / len(df)
df["Average"] = average_goal
print(df)
print("Average Goals:", average_goal)

       player  Goals  Assists  Matches  Goal_per_match Above_Average_goals  \
0     Ronaldo   1000      400     1100        0.909091          Top player
1       Messi    900      500     1000        0.900000          Top player
2      Mbappe    500      200      500        1.000000          Top player
3      Vinijr    200      100      500        0.400000       Normal player
4      Neymar    400      300      600        0.666667       Normal player
5   Belingham    200      100      400        0.500000       Normal player
6  Nunomendes    100      100      300        0.333333       Normal player

      Average
0  471.428571
1  471.428571
2  471.428571
3  471.428571
4  471.428571
5  471.428571
6  471.428571
Average Goals: 471.42857142857144

In [19]:
top_scorer = df[df["Goals"] == df["Goals"].max()]
print(top_scorer)

    player  Goals  Assists  Matches  Goal_per_match
0  Ronaldo   1000      400     1100        0.909091

In [34]:
average= df["Goals"].mean()
above_average_goals = []
for value in df["Goals"]:
    if value >= average:
        above_average_goals.append("Top player")
    else:
        above_average_goals.append("Normal player")
df["Above_Average_goals"]=above_average_goals
print(df)

       player  Goals  Assists  Matches  Goal_per_match Above_Average_goals  \
0     Ronaldo   1000      400     1100        0.909091          Top player
1       Messi    900      500     1000        0.900000          Top player
2      Mbappe    500      200      500        1.000000          Top player
3      Vinijr    200      100      500        0.400000       Normal player
4      Neymar    400      300      600        0.666667       Normal player
5   Belingham    200      100      400        0.500000       Normal player
6  Nunomendes    100      100      300        0.333333       Normal player

      Average
0  471.428571
1  471.428571
2  471.428571
3  471.428571
4  471.428571
5  471.428571
6  471.428571

In [40]:
Total = df["Goals"].sum()
print(total)
df

3300

,player,Goals,Assists,Matches,Goal_per_match,Above_Average_goals,Average
0,Ronaldo,1000,400,1100,0.909091,Top player,471.428571
1,Messi,900,500,1000,0.900000,Top player,471.428571
2,Mbappe,500,200,500,1.000000,Top player,471.428571
3,Vinijr,200,100,500,0.400000,Normal player,471.428571
4,Neymar,400,300,600,0.666667,Normal player,471.428571
5,Belingham,200,100,400,0.500000,Normal player,471.428571
6,Nunomendes,100,100,300,0.333333,Normal player,471.428571