In [4]:
import pandas as pd

In [5]:

df = pd.DataFrame({
    "name": ["Ram", "Shyam", "Hari"],
    "math": [99, 76, 67],
    "science": [89, 65, 76],
    "english": [65, 43, 65]
})

In [6]:
df["passed"] = (
    (df["math"] >= 60) &
    (df["science"] >= 60) &
    (df["english"] >= 60)
)

print(df)

    name  math  science  english  passed
0    Ram    99       89       65    True
1  Shyam    76       65       43   False
2   Hari    67       76       65    True

In [47]:
fail_student = df[~df["passed"]]
fail_student

    name  math  science  english  passed
1  Shyam    76       65       43   False

In [53]:
result = []

for value in df["passed"]:
    if value:
        result.append("pass")
    else:
        result.append("fail")
df["Result"] = result
df

    name  math  science  english  passed Result
0    Ram    99       89       65    True   pass
1  Shyam    76       65       43   False   fail
2   Hari    67       76       65    True   pass

In [55]:
fail_student = df[df["Result"] == "fail"]
fail_student

    name  math  science  english  passed Result
1  Shyam    76       65       43   False   fail

In [66]:
count = 0
for values in  df["Result"]:
    if values =="pass":
       count+=1
print("passing student:",count)

passing student: 2

In [67]:
count = 0
for values in  df["Result"]:
    if values =="fail":
       count+=1
print("failing student:",count)

failing student: 1

In [70]:
df["total"] = df["math"] + df["science"] + df["english"]
df

    name  math  science  english  passed Result  total
0    Ram    99       89       65    True   pass    253
1  Shyam    76       65       43   False   fail    184
2   Hari    67       76       65    True   pass    208

In [75]:
highest = -1
topper = ""
for i in range(len(df)):
    if df.loc[i,"total"]>highest:
        highest = df.loc[i,"total"]
        topper = df.loc[i,"name"]
print("topper:",topper)
print("Marks:",highest)

topper: Ram
Marks: 253

In [78]:
lowest = df.loc[0,"total"]
student = df.loc[0,"name"]

for i in range(1,len(df)):
    if df.loc[i,"total"]<lowest:
        lowest = df.loc[i,"total"]
        student= df.loc[i,"name"]
print("Name:",student)
print("lowest mark:",lowest)

Name: Shyam
lowest mark: 184

In [79]:
highest = df["total"].max()
print(highest)

253

In [81]:
lowest =df["total"].min()
print(lowest)

184

In [82]:
highest = df["total"].max()

topper = df[df["total"] == highest]

print(topper)

  name  math  science  english  passed Result  total
0  Ram    99       89       65    True   pass    253

In [95]:
subjects = ["math", "science", "english"]

df["average"] = df[subjects].mean(axis=1)
print(df)

    name  math  science  english  passed Result  total    average
0    Ram    99       89       65    True   pass    253  84.333333
1  Shyam    76       65       43   False   fail    184  61.333333
2   Hari    67       76       65    True   pass    208  69.333333

In [94]:
subjects = ["math", "science", "english"]
average = []
for i in range(len(df)):
    total = 0
    for subject in subjects:
        total += df.loc[i,subject]
    average.append(total/len(subjects))

df["average"]=average
print(df)

    name  math  science  english  passed Result  total    average
0    Ram    99       89       65    True   pass    253  84.333333
1  Shyam    76       65       43   False   fail    184  61.333333
2   Hari    67       76       65    True   pass    208  69.333333

In [104]:
grades=[]
for average in df["average"]:
    if average>=80:
        grades.append("A")
    elif average>=60:
        grades.append("B")
    else:
        grades.append("C")
df["Grade"]=grades
print(df)

    name  math  science  english  passed Result  total    average Grade
0    Ram    99       89       65    True   pass    253  84.333333     A
1  Shyam    76       65       43   False   fail    184  61.333333     B
2   Hari    67       76       65    True   pass    208  69.333333     B

In [108]:
grades = []

for i in range(len(df)):
    if (df.loc[i, "math"] < 60 or
        df.loc[i, "science"] < 60 or
        df.loc[i, "english"] < 60):
       
        grades.append("NG")

    elif df.loc[i, "average"] >= 80:
        grades.append("A+")

    elif df.loc[i, "average"] >= 60:
        grades.append("B+")

    else:
        grades.append("Fail")

df["Grade"] = grades

print(df)

    name  math  science  english  passed Result  total    average Grade
0    Ram    99       89       65    True   pass    253  84.333333    A+
1  Shyam    76       65       43   False   fail    184  61.333333    NG
2   Hari    67       76       65    True   pass    208  69.333333    B+