In [31]:
import pandas as pd

In [34]:
student = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "name":["ram","sita","hari","gita","som"],
    "subject": ["math", "science", "health", "AI", "ML"]
})

score = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "city": ["Kathmandu", "Pokhara", "Kohalpur", "Nepalgunj", "Kathmandu"],
    "score": [77, 65, 45, 54, 76]
})

In [35]:
student.to_csv("students.csv", index=False)
score.to_csv("scores.csv", index = False)

In [36]:
student

   id  name  subject
0   1   ram     math
1   2  sita  science
2   3  hari   health
3   4  gita       AI
4   5   som       ML

In [37]:
score

   id       city  score
0   1  Kathmandu     77
1   2    Pokhara     65
2   3   Kohalpur     45
3   4  Nepalgunj     54
4   5  Kathmandu     76

In [38]:
merged_df = pd.merge(student, score, on="id")

In [39]:
merged_df

   id  name  subject       city  score
0   1   ram     math  Kathmandu     77
1   2  sita  science    Pokhara     65
2   3  hari   health   Kohalpur     45
3   4  gita       AI  Nepalgunj     54
4   5   som       ML  Kathmandu     76

In [40]:
merged_df.groupby("city")

In [46]:
merged_df.groupby("subject")["score"].mean()

subject
AI         54.0
ML         76.0
health     45.0
math       77.0
science    65.0
Name: score, dtype: float64

In [47]:
merged_df.groupby("city")["score"].mean()

city
Kathmandu    76.5
Kohalpur     45.0
Nepalgunj    54.0
Pokhara      65.0
Name: score, dtype: float64

In [51]:
high_scores = merged_df[merged_df["score"] == merged_df["score"].max()]

high_scores

   id name subject       city  score
0   1  ram    math  Kathmandu     77

In [54]:
summary = merged_df.groupby("city").agg({
    "score": "mean",
    "name": "count"
}).reset_index()

summary

        city  score  name
0  Kathmandu   76.5     2
1   Kohalpur   45.0     1
2  Nepalgunj   54.0     1
3    Pokhara   65.0     1

In [56]:
merged_df.sort_values(by="score", ascending=False)

   id  name  subject       city  score
0   1   ram     math  Kathmandu     77
4   5   som       ML  Kathmandu     76
1   2  sita  science    Pokhara     65
3   4  gita       AI  Nepalgunj     54
2   3  hari   health   Kohalpur     45