In [4]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("student.csv")
df

   ID    Name Gender  Math  Science  English
0   1  Aayush      M    85       78       90
1   2     Ram      M    70       82       76
2   3    Sita      F    92       88       95
3   4    Gita      F    65       72       70
4   5    Hari      M    80       75       85
5   6    Rita      F    95       90       98
6   7   Bibek      M    60       68       65
7   8    Nita      F    88       84       91
8   9   Kiran      M    73       77       80
9  10  Anisha      F    90       93       89

In [9]:
df.head()

   ID    Name Gender  Math  Science  English
0   1  Aayush      M    85       78       90
1   2     Ram      M    70       82       76
2   3    Sita      F    92       88       95
3   4    Gita      F    65       72       70
4   5    Hari      M    80       75       85

In [10]:
df.tail()

   ID    Name Gender  Math  Science  English
5   6    Rita      F    95       90       98
6   7   Bibek      M    60       68       65
7   8    Nita      F    88       84       91
8   9   Kiran      M    73       77       80
9  10  Anisha      F    90       93       89

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       10 non-null     int64
 1   Name     10 non-null     str
 2   Gender   10 non-null     str
 3   Math     10 non-null     int64
 4   Science  10 non-null     int64
 5   English  10 non-null     int64
dtypes: int64(4), str(2)
memory usage: 612.0 bytes

In [12]:
df.describe()

             ID       Math    Science    English
count  10.00000  10.000000  10.000000  10.000000
mean    5.50000  79.800000  80.700000  83.900000
std     3.02765  12.163698   8.124722  10.877602
min     1.00000  60.000000  68.000000  65.000000
25%     3.25000  70.750000  75.500000  77.000000
50%     5.50000  82.500000  80.000000  87.000000
75%     7.75000  89.500000  87.000000  90.750000
max    10.00000  95.000000  93.000000  98.000000

In [13]:
df.shape

(10, 6)

In [15]:
df.columns

Index(['ID', 'Name', 'Gender', 'Math', 'Science', 'English'], dtype='str')

In [16]:
df.dtypes

ID         int64
Name         str
Gender       str
Math       int64
Science    int64
English    int64
dtype: object

In [17]:
df.isnull().sum()

ID         0
Name       0
Gender     0
Math       0
Science    0
English    0
dtype: int64

In [18]:
df["Name"]

0    Aayush
1       Ram
2      Sita
3      Gita
4      Hari
5      Rita
6     Bibek
7      Nita
8     Kiran
9    Anisha
Name: Name, dtype: str

In [19]:
df[["Name", "Math"]]

     Name  Math
0  Aayush    85
1     Ram    70
2    Sita    92
3    Gita    65
4    Hari    80
5    Rita    95
6   Bibek    60
7    Nita    88
8   Kiran    73
9  Anisha    90

In [20]:
df[df["Math"] > 80]

   ID    Name Gender  Math  Science  English
0   1  Aayush      M    85       78       90
2   3    Sita      F    92       88       95
5   6    Rita      F    95       90       98
7   8    Nita      F    88       84       91
9  10  Anisha      F    90       93       89

In [21]:
df[df["Gender"] == "F"]

   ID    Name Gender  Math  Science  English
2   3    Sita      F    92       88       95
3   4    Gita      F    65       72       70
5   6    Rita      F    95       90       98
7   8    Nita      F    88       84       91
9  10  Anisha      F    90       93       89

In [22]:
df[df["Gender"] == "M"]

   ID    Name Gender  Math  Science  English
0   1  Aayush      M    85       78       90
1   2     Ram      M    70       82       76
4   5    Hari      M    80       75       85
6   7   Bibek      M    60       68       65
8   9   Kiran      M    73       77       80

In [24]:
df["Total"] = df["Math"] + df["Science"] + df["English"]
df

   ID    Name Gender  Math  Science  English  Total
0   1  Aayush      M    85       78       90    253
1   2     Ram      M    70       82       76    228
2   3    Sita      F    92       88       95    275
3   4    Gita      F    65       72       70    207
4   5    Hari      M    80       75       85    240
5   6    Rita      F    95       90       98    283
6   7   Bibek      M    60       68       65    193
7   8    Nita      F    88       84       91    263
8   9   Kiran      M    73       77       80    230
9  10  Anisha      F    90       93       89    272

In [26]:
df["Average"] = df["Total"] / 3
df

   ID    Name Gender  Math  Science  English  Total    Average
0   1  Aayush      M    85       78       90    253  84.333333
1   2     Ram      M    70       82       76    228  76.000000
2   3    Sita      F    92       88       95    275  91.666667
3   4    Gita      F    65       72       70    207  69.000000
4   5    Hari      M    80       75       85    240  80.000000
5   6    Rita      F    95       90       98    283  94.333333
6   7   Bibek      M    60       68       65    193  64.333333
7   8    Nita      F    88       84       91    263  87.666667
8   9   Kiran      M    73       77       80    230  76.666667
9  10  Anisha      F    90       93       89    272  90.666667

In [27]:
topper = df.loc[df["Total"].idxmax()]
topper

ID                 6
Name            Rita
Gender             F
Math              95
Science           90
English           98
Total            283
Average    94.333333
Name: 5, dtype: object